### ISSUE TITLE
the List argument for the SUBLIST function seems absurd

### ISSUE THREAD

**Issue by JeanBaptistePelliccia** [senx/warp10-platform#1017]
the List argument for the SUBLIST function, do différent things depending on the number of element in the list. This argument seems to act like the arguments start end for the same fonction when the list is of size 2 and when the size is different of 2 it seems to act like the fonction GET with the elements of the list on the top of the stack as index .

Example : 

`
[ 0 1 2 3 4 ] [ 1 3 ] SUBLIST 

[ 0 1 2 3 4 ] [ 1 ] SUBLIST 

[ 0 1 2 3 4 ] [ 1 3 4 ] SUBLIST 

`

**Comment by ftence** [comment]
This is the expected behavior according to the documentation. I do agree that this is strange but we cannot change that as some production code may depend on that behavior.

Maybe we could change that in the next major release, this is open to discussion.
