### ISSUE TITLE
Adding data with attribute does not seem to reflect properly on Warp 10 studio 

### ISSUE THREAD

**Issue by ksVivien** [senx/warp10-platform#1093]
Data sent via Warp 10's studio 
![image](https://user-images.githubusercontent.com/105765655/168952040-d5c98116-8056-4cdf-910a-94691e3883ea.png)

Fetched data seems to not include the attribute
![image](https://user-images.githubusercontent.com/105765655/168952109-3d5f195c-03a0-435b-9756-888f486e7a5f.png)

Curl command: 
curl --location -g --request GET 'http://localhost:8080/api/v0/fetch?start=2022-01-01T13%3A30%3A00.000Z&stop=2022-06-18T13%3A30%3A00.000Z&selector=~.*{}&format=fulltext&dedup=true' \
--header 'X-Warp10-Token: [token]'

**Comment by darwinsubramaniam** [comment]
Facing the same issue .

**Comment by hbs** [comment]
Hi,

the parsing of attributes is not on by default, it has to be enabled via the following configurations:

# Set to true to parse attributes in the data passed to /update.
ingress.parse.attributes = true

# Set to true to allow attributes to be interpreted as a delta update
#ingress.attributes.allowdelta = true


If ingress.parse.attributes is set to true but you are not seeing the attributes as being updated then there is indeed an issue.

**Comment by ksVivien** [comment]
Hi, 

Sorry, I'm new to these configurations. May I check about I can configure the docker file to have this settings enable? 
Thank you!

**Comment by hbs** [comment]
If you have launched the docker container with an external /data volume, edit the file `warp10/etc/config.d/10-ingress.conf` and set the configuration as below:

```
ingress.parse.attributes = true
```
