### ISSUE TITLE
Bucketize not working perfectly in latest version

### ISSUE THREAD

**Issue by nidgup89** [senx/warp10-platform#1276]
100  NaN NaN NaN 10 ADDVALUE
100  NaN NaN NaN 10 ADDVALUE
200  NaN NaN NaN  9 ADDVALUE
200  NaN NaN NaN  9 ADDVALUE
300  NaN NaN NaN  8 ADDVALUE
300  NaN NaN NaN  8 ADDVALUE
400  NaN NaN NaN  7 ADDVALUE
400  NaN NaN NaN  7 ADDVALUE
500  NaN NaN NaN  6 ADDVALUE
500  NaN NaN NaN  6 ADDVALUE
600  NaN NaN NaN  5 ADDVALUE
700  NaN NaN NaN  4 ADDVALUE
**800  NaN NaN NaN 42 ADDVALUE
800  NaN NaN NaN 42 ADDVALUE
800  NaN NaN NaN 42 ADDVALUE**
[ SWAP bucketizer.count 0 100 0 ] BUCKETIZE trying to use this getting result -
[{"c":"","l":{},"a":{},"la":0,"v":[[**800,2**],[700,1],[600,1],[500,2],[400,2],[300,2],[200,2],[100,2]]}] but see we have 3 values for 800.

**Comment by hbs** [comment]
Fixed by #1277
