### ISSUE TITLE
Warp Studio Behaving differently with Data Stored in the DB versus Data parsed in the memory 

### ISSUE THREAD

**Issue by nidgup89** [senx/warp10-platform#1278]
I am working on a dataset (9.4 MB). Tries storing and fetching the data , not able to see the plot getting issues.
<img width="1233" alt="image" src="https://github.com/senx/warp10-platform/assets/19973170/3da35e05-aa79-41e7-850c-182dab386228">

<img width="669" alt="image" src="https://github.com/senx/warp10-platform/assets/19973170/3fbd9aa5-89b5-4a64-9696-16829033ba84">

Able to plot the same data when parsed in the memory like this - <'1578216981// volts1{dut=SIM%202} 0.10054042
1578216982// volts1{dut=SIM%202} 0.100866201
1578216983// volts1{dut=SIM%202} 0.101191982
1578216984// volts1{dut=SIM%202} 0.101517763
1578216985// volts1{dut=SIM%202} 0.101843544
1578216986// volts1{dut=SIM%202} 0.103146668
1578216987// volts1{dut=SIM%202} 0.106730259
       '>
       PARSE

**Comment by steven-gueguen** [comment]
Can you retrieve some data with a curl command, for example:
`curl -g 'http://your-warp10-instance:8080/api/v0/fetch?token=YOUR-READ-TOKEN&selector=volts1{}&start=1960-01-01T00:00:00.000Z&end=2015-01-01T00:00:00.000Z'`

**Comment by Giwi** [comment]
Hi, it is a Discovery related issue (https://github.com/senx/discovery-widgets) and it is fixed in https://github.com/senx/discovery-widgets/releases/tag/v1.1.87. Therefore, i have to deploy it (today) in WarpStudio.
