### ISSUE TITLE
jdk17 breaks GOLDWRAP

### ISSUE THREAD

**Issue by pi-r-p** [senx/warp10-platform#1307]
```
NEWGTS
    1 DUP DUP DUP -1 ADDVALUE
    2 DUP DUP DUP 1 ADDVALUE
    3 DUP DUP DUP MINLONG ADDVALUE
    4 DUP DUP DUP MAXLONG ADDVALUE
    5 DUP DUP DUP 0 ADDVALUE
GOLDWRAP ->OPB64
"T37UXkV.........DyE2S7.dSkg7BI6qy23SsClq.NHNa3.R4FWVyVw2Y6p.JQMQ2X.3JPzjx.L3a0V.jDemL3c....L1W3."

```

**Comment by hbs** [comment]
What does it break?

**Comment by pi-r-p** [comment]
JDK8:
```
  "T37UXkV.........DyE2S7.dSkg7BI6qy23SsClq.NHNa3.R4FWVyVw2Y6p.JQMQ2X.3JPzjx.L3a0V.jDemL3c....L1W3."
```
JDK17:
```
  "T37UXkV.......2zDyE2S7.dSkg7BI6qy23SsClq.NHNa3.R4FWVyVw2Y6p.JQMQ2X.3JPzjx.L3a0V.jDemL3c....L1W3." 
```

**Comment by hbs** [comment]
The GZIP header generated by the different JDK versions seem to differ. JDK8 generates:

`0x1f8b0800000000000000`

while JDK17 generates

`0x1f8b08000000000000ff`

The two differ on the last byte which is the operating system ID. JDK8 outputs `0x00` meaning `FAT filesystem` while JDK17 outputs `0xff` meaning Unknown (as per RFC1952).

We could force the operating system ID to `0x00` in `GTSWrapperHelper#fromGTSEncoderToGTSWrapper` so the various rounds of compression all output this value.
