### ISSUE TITLE
SHRINK does not alter bucketize status

### ISSUE THREAD

**Issue by randomboolean** [senx/warp10-platform#1310]
SHRINK on bucketized GTS does not modify bucketcount nor lastbucket.

Shrinked bucketized GTS end up with lastbuckets that are not aligned with their last data point.

Fix options:
- reset bucketize status in shrink (unbucketize)
- or update bucketize parameters in shrink (but must account for non bucket data points)
- or precise in shrink documentation the current behavior

**Comment by hbs** [comment]
SHRINK is focused on restricting the number of values, the bucketization parameters should not be altered as a result, so your last option is the one to adopt.

**Comment by randomboolean** [comment]
Documentation has been modified.
