### ISSUE TITLE
No default limits for applications

### ISSUE THREAD

**Issue by d33d33** [senx/warp10-platform#178]
Default limits are available for producers but not for applications.

What about adding: `DEFAULT_MADS_APPLICATION` and `DEFAULT_RATE_APPLICATION`?

**Comment by hbs** [comment]
This was intentional, we expect limits to be set explicitly for
applications as there can be many of them and that a default limit would
imply to allocate an estimator for every application.

Please open an issue so we keep a note on this request, we need to think
about the implications first.
