### ISSUE TITLE
Expose an admin API

### ISSUE THREAD

**Issue by StevenLeRoux** [senx/warp10-platform#239]
Platform management sometimes require an admin API available for some warp10 components (directory, ingress, egress) to overwrite some configuration parameters

A first example is this one : 

> I want to control ZK registering for a directory in real time.
> 
> If a directory is stopped for a long time (e.g. hours), when starting again it will consume from the last Kafka offset to be synced. While being out of sync, even if a directory is started with `directory.register = true`
> I would like to tell him to unregister, and then register back when synced.
> This should not be a strategy inside the Directory itself because if all directories are lagging, one could prefer a best effort selector lookup over blocking find requests.

A way to perform this is by controlling from outside a directory instance, with an admin API.
It would be useful for other parameters to be available through an API. Parameters like : 

- limits
- plugins
- ...

Playing with configuration alteration & restarting doesn't seem a proper way to manage this need.

tags:enhancement

**Comment by hbs** [comment]
You can probably play with the znode permissions to do what you want.

Configuration is loaded at startup and propagated to the launched components, they do not 'listen' to the configuration so this would induce heavy changes and some of the parameters cannot be changed altogether.

**Comment by hbs** [comment]
In the case of Directory, when Directory starts it will first read HBase, then it will consume Kafka, so out of sync period is normally limited, and can be in any case mitigated by stopping and starting the directory with varying parameters for the offset reset strategy after having deleted offsets from ZK for this particular directory instance.
