### ISSUE TITLE
Authentication: introduce other methods than warp10 token

### ISSUE THREAD

**Issue by waxzce** [senx/warp10-platform#268]
recently, we discover the need of being able to delegate a subpart of the authorisation of a token, like we do in macaroon.

I'm not confident about W10Token evolution without breaking things, and for a various reason get proper macaroons can be a good thing. But macaroons are way longer than w10tk. That's why I think a warp10 cluster will profit of multiple authentication methods.

In the warp script we will change nothing, get token as usual but prefix with an alternative when it's not a warp10 token (ie "macaroon:", "userpassword:"...). This way we can provide a various way to connect to the w10 cluster.

What do you think?

Do we want to be able to build auth extensions also outside of the w10 codebase? With a dynamic classloader plugin system? Or built in in the core?

Where do I have to plug this?

**Comment by hbs** [comment]
Right now the token extraction mechanism is not pluggable, we'll push a PR shortly to allow such plugins. The interface will be rather simple, with two methods to extract read and write tokens.

Stay tuned.

**Comment by hbs** [comment]
Please check PR #274, it shows an example of AuthenticationPlugin.

**Comment by waxzce** [comment]
I'll check it out soon

**Comment by divarvel** [comment]
Great! I can work on a macaroon support plugin this week (hopefully) or next week.

**Comment by waxzce** [comment]
Seems very nice. It's awesome. My only concern is the WarpScriptException, I think it can be a good idea to create a specific subclass like InvalidTokenWarpScriptException for debug purpose. What do you think about @hbs ?

**Comment by hbs** [comment]
The exceptions thrown in Tokens are caught by the various WarpScript functions which do not differentiate any subclass of WarpScriptException, so this would be of little benefit for debug purposes.

**Comment by hbs** [comment]
That could be a plus, but the owner/producer uuids and applications would still have to be defined in the .htpasswd like file though, simple login/password would be sufficient only for the authentication, not for building the read/write tokens.

**Comment by waxzce** [comment]
As soon as the PR #274 is merged, I think we can close this issue
