### ISSUE TITLE
Add Macaroon as auth method on warp10

### ISSUE THREAD

**Issue by waxzce** [senx/warp10-platform#280]
To be able to delegate auth easily. 

depends of #268

**Comment by waxzce** [comment]
cc @divarvel

**Comment by divarvel** [comment]
I'll open a WIP Pull Request and write down the spec in it.

**Comment by hbs** [comment]
Please create a third party repo for this plugin.

**Comment by divarvel** [comment]
Sure. I'll take inspiration from ﻿﻿https://github.com/cityzendata/warp10-quantum-plugin (maybe there is documentation on plugins somewhere, but I haven't found it)

**Comment by hbs** [comment]
The quantum plugin is a generic plugin, not an authentication plugin, check the AuthExampleWarp10Plugin from PR #274

**Comment by hbs** [comment]
There is not (yet) a template repo for authentication plugins, you can work from the template for Warp 10 plugins or WarpScript extensions

https://github.com/cityzendata/warp10-plugin-template
https://github.com/cityzendata/warp10-ext-template

**Comment by waxzce** [comment]
BTW the plugin is working CleverCloud/warp10-macaroons-plugin
