### ISSUE TITLE
[Auth] Convenient Login/Password auth module

### ISSUE THREAD

**Issue by waxzce** [senx/warp10-platform#283]
As discuss with @hbs 

Me:
Do you want we add a login/password plugin reading htpassw like file to help people at start?

@hbs:
That could be a plus, but the owner/producer uuids and applications would still have to be defined in the .htpasswd like file though, simple login/password would be sufficient only for the authentication, not for building the read/write tokens.

It can be integrated as simple auth system, convenient for testing or for CI for example

depends of #268

**Comment by hbs** [comment]
With the availability of the authentication plugin mechanism, this can now be implemented as a Warp 10 plugin. Closing this as it is not directly a Warp 10 platform issue.

**Comment by waxzce** [comment]
Do you want I write a plugin you can default include?
