### ISSUE TITLE
[WarpScript] reducer.median returns NULL error

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#393]
Hi, 
Starting from reducer.median the example, and removing one tick from one series as below:
`
[
  [
    NEWGTS "GTS1" RENAME 
    10 NaN NaN NaN 1 ADDVALUE
    20 NaN NaN NaN 5 ADDVALUE
    
    NEWGTS "GTS2" RENAME 
    10 NaN NaN NaN 4 ADDVALUE
    20 NaN NaN NaN 3 ADDVALUE

    NEWGTS "GTS3" RENAME 
    10 NaN NaN NaN 3 ADDVALUE
    20 NaN NaN NaN 8 ADDVALUE

    NEWGTS "GTS4" RENAME 
    10 NaN NaN NaN 3 ADDVALUE
  ] [] reducer.median
] REDUCE
`

And then executing the WarpScript returns:
`
ERROR line #18 in section '[TOP]': null
`

**Comment by hbs** [comment]
Good catch, thanks.
