### ISSUE TITLE
Documentation example : format attribute in fetch

### ISSUE THREAD

**Issue by Liberasys** [senx/warp10-platform#399]
In page : [https://www.warp10.io/content/03_Documentation/06_Operations/06_Dumps_and_load](https://www.warp10.io/content/03_Documentation/06_Operations/06_Dumps_and_load)

We see:
`$ curl 'http(s)://<Warp 10 url>/api/v0/fetch?token=<read token>&selector=~.*\{\}&start=2019-01-01T00:00:00.000000Z&stop=2000-01-01T00:00:00.000000Z&timespan=-1&text' > snap.txt`

I think it should be:
`$ curl 'http(s)://<Warp 10 url>/api/v0/fetch?token=<read token>&selector=~.*\{\}&start=2019-01-01T00:00:00.000000Z&stop=2000-01-01T00:00:00.000000Z&timespan=-1&format=text' > snap.txt`

And a suggestion : insert format attribute in example in page [https://www.warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/04_Fetching_data/01_Fetching_data](https://www.warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/04_Fetching_data/01_Fetching_data):

`GET /api/v0/fetch?now=1435091737000000&timespan=-10&selector=io.warp10.test.sinusoide{steps=100} HTTP/1.1`

suggested:
`[GET /api/v0/fetch?now=1435091737000000&timespan=-10&format=fulltext&selector=io.warp10.test.sinusoide{steps=100} HTTP/1.1](url)`

BR
Gautier HUSSON.

**Comment by hbs** [comment]
Good catch, the pages have been modified, will be online shortly.
