### ISSUE TITLE
Deactivate REXEC

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#411]
REXEC since Warp10 2.0 is now a Warp 10 extension. Migrating to Warp 10 2.0 break the behavior of some scripts as the REXEC function isn't allowed. 
To resolve this issue we can simply keep a Warp 10 properties to allow the administrator to disable the REXEC extension?

**Comment by hbs** [comment]
You can use the bootstrap mechanism to define an REXEC function which does nothing thus providing an REXEC function which basically is an alias for NOOP.
