### ISSUE TITLE
NONNULL operator does not works as describe in the documentation

### ISSUE THREAD

**Issue by FlorentinDUBOIS** [senx/warp10-platform#421]
Hello,

I tried to use the following example on Warp 10 2.0, but this does not work as describe on the documentation of [NONNULL](https://www.warp10.io/doc/NONNULL#sigTitle):

```
[ 'foo' 'bar' NULL ] <% NONNULL %> FILTERBY 
```

I expect the following list on the stack:

```json
["foo", "bar"]
```

but instead I got this:

```
ERROR line #1 in section '[TOP]': NONNULL operates on a list.
```

The workaround is to do something like this:

```
[ 'foo' 'bar' NULL ] NONNULL
```

**Comment by hbs** [comment]
Indeed the documentation is incorrect. For your case instead of <% NONNULL %>, use <% ISNULL NOT %>.

Fixing the documentation, thanks for the head up.

**Comment by hbs** [comment]
Documentation has been fixed, will de deployed shortly. Thanks again.
