### ISSUE TITLE
MAXLONG and MAP bug

### ISSUE THREAD

**Issue by bensmrs** [senx/warp10-platform#438]
Hi,
There is a problem when mapping using MAXLONG. See below:
```
[
  [
    NEWGTS
    10 NaN NaN NaN  42.0 ADDVALUE
    20 NaN NaN NaN 123.0 ADDVALUE
    30 NaN NaN NaN 211.0 ADDVALUE
    40 NaN NaN NaN 132.0 ADDVALUE
  ]
  mapper.max
  MAXLONG
  0
  -3
] MAP
```
is expected to return `[{"c":"","l":{},"a":{},"la":0,"v":[[40,211],[30,211],[20,123]]}]`, but returns `[{"c":"","l":{},"a":{},"la":0,"v":[[40,211]]}]`.
If you replace `MAXLONG` by `MAXLONG 2 /`, you get the desired result.

**Comment by hbs** [comment]
Fixed, thanks for the head up.
