### ISSUE TITLE
Macro returning another macro

### ISSUE THREAD

**Issue by bensmrs** [senx/warp10-platform#447]
Hi!

I'm trying to make a macro that returns another macro in such a way that the returned macro doesn't try to load any symbol. For example, I want a macro `hello` that works this way: `'world' @hello` returns `<% 'hello' 'world' + %>`. I would have guessed that `!$symbol` looks for `$symbol` in the outer macro, such that
```
<%
  'a' STORE
  <% 'hello' !$a + %>
%>
```
works, but unfortunately, it only looks for symbols in the global scope (giving me a nice `Unknown symbol 'a'` error). Is this behaviour expected, and if so, is there a way to achieve what I'm asking?

Thanks

**Comment by hbs** [comment]
You need to defer the evaluation of the macro you build, this is easily done with the following construct:

<%
  'a' STORE
  <'
  <% 'hello' !$a + %>
  '>
  EVAL
%>

**Comment by bensmrs** [comment]
Great, thanks a lot!
I thought inner macros were defered by default. Maybe it deserves a little explanation in the documentation? Anyway, that was the feature I missed when I started to learn Warp 10 and I'm glad it is achievable.

**Comment by hbs** [comment]
The macro construction happens when the macro is first encountered, which is at the time the outer macro is built. The immediate variable dereference !$var happens, well, immediately when the construct is encountered, so in your initial case when the outer macro was built, not when it was being used.

**Comment by hbs** [comment]
The binding rules are somehow explained in this [blog post](https://blog.senx.io/thinking-in-warpscript-authoring-macros/)
