### ISSUE TITLE
Add mapper.not function

### ISSUE THREAD

**Issue by fredduwez** [senx/warp10-platform#454]
Simple mapper that apply a NOT to all values.

**Comment by pi-r-p** [comment]
Finally, we won't implement mapper.not, but an extension of booleans operators on gts : 
`$gts !` will be easier and faster to apply a NOT on all values. 
`$gtslist <% DROP ! %> LMAP` to apply it on a list of gts.

&& and || will also be available to do logic conditions easily on 2 aligned gts.

**Comment by hbs** [comment]
Closing it, check #456 for the alternate solution
