### ISSUE TITLE
JSON serialization error on Fetch

### ISSUE THREAD

**Issue by dweeves** [senx/warp10-platform#467]
Hi,

I noticed JSON format output is invalid for "la" field, 

=> "la":0" is not valid JSON
=> "la":"0" should be the valid output

I needed to mask some labels for confientiality

Sample data :
`
{"c":"xxx","l":{"sens":"Retour".app":"io.warp10.bootstrap","num_arret":"1663","id_type_titre":"1","numero_de_la_ligne":"207"},"a":{},"i":"108130483266709504,"la":0","v":[[1539583200000,-1.6705980012193322,48.1042109336704,4]]},{"c":"xxx","l":{"sens":"Aller",".app":"io.warp10.bootstrap","num_arret":"1663","id_type_titre":"1","numero_de_la_ligne":"41"},"a":{},"i":"284291214830745600,"la":0","v":[[1539667800000,-1.6705980012193322,48.1042109336704,2]]}`

**Comment by hbs** [comment]
This should already be solved in HEAD on master

**Comment by hbs** [comment]
Do you confirm that the solution to #442 solves your issue?

**Comment by hbs** [comment]
Indeed fixed on HEAD
