### ISSUE TITLE
Slow APPLY operations when filtering with labels

### ISSUE THREAD

**Issue by GillesBIANNIC** [senx/warp10-platform#479]
With a bucketized dataset of:
- a list of 1600 GTS named A with only one point inside, having two labels ("host" and "disk").
- another list of GTS, same conditions, but named B.
Every combination of host + disk in labels makes the gts unique (in A and B).

I want to add each unique combination of gts A to B:
`[ $a $b [ 'host' 'disk' ] op.add ] APPLY`

It works, but it's very slow on a recent warp:
On a old warp 1.2.22-88, it took less than 1000ms.
On a recent warp 2.0.2-162, the APPLY alone takes more than 4500ms every time.

I tested to divide each combination by myself like this:
```
$a [ 'host' 'disk' ] PARTITION 'pa' STORE
$b [ 'host' 'disk' ] PARTITION
[] SWAP
<%
   'series' STORE
   'labels' STORE
   [ 
      $series
      $pa $labels GET
      [] 
      op.add 
   ] APPLY
   APPEND
%>
FOREACH
```
... and it took ~100ms.

I am a bit worried here about the low performance with the APPLY function. I am searching about what could be responsible for it.
What would be the best way to perform this operation?

PS: All time measurements has been done in the WarpScript with NOW time subtractions around the APPLY.

**Comment by hbs** [comment]
Can you provide an example dataset?

Also can you try applying PARTITION instead of APPLY, there is a great chance that most of the time is spent in the partitioning phase.

**Comment by GillesBIANNIC** [comment]
Code with dataset:

```
1600 'n' STORE

[] 'a' STORE
1 $n
<%
    'i' STORE
    NEWGTS
    {
        'host' 'host-' $i TOSTRING +
        'disk' 'disk-' $i TOSTRING +
    }
    RELABEL
    'gts A' RENAME
    1 NaN NaN NaN $i ADDVALUE
    $a SWAP +! DROP
%>
FOR
$a 'name-list-a' RENAME 'a' STORE

[] 'b' STORE
1 $n
<%
    'i' STORE
    NEWGTS
    {
        'host' 'host-' $i TOSTRING +
        'disk' 'disk-' $i TOSTRING +
    }
    RELABEL
    1 NaN NaN NaN $i ADDVALUE
    $b SWAP +! DROP
%>
FOR
$b 'name-list-b' RENAME 'b' STORE

NOW
[ $a $b [ 'host' 'disk' ] op.add ] APPLY DROP
NOW SWAP -
HUMANDURATION 'Time with APPLY: ' SWAP + 'time_apply' STORE

NOW
$a [ 'host' 'disk' ] PARTITION 'pa' STORE
$b [ 'host' 'disk' ] PARTITION
[] SWAP
<%
    'series' STORE
    'labels' STORE
    [ 
       $series
       $pa $labels GET
       [] 
       op.add 
    ] APPLY
    APPEND
%>
FOREACH DROP
NOW SWAP -
HUMANDURATION 'Time with PARTITION: ' SWAP + 'time_partition' STORE

NOW
[ $a $b APPEND [ 'host' 'disk' ] reducer.sum ] REDUCE DROP
NOW SWAP -
HUMANDURATION 'Time with REDUCE: ' SWAP + 'time_reduce' STORE

$time_apply
$time_partition
$time_reduce
```

Results:
0: "Time with REDUCE: 0.018644s"
1: "Time with PARTITION: 0.024088s"
2: "Time with APPLY: 2.773569s"

**Comment by hbs** [comment]
Can you try with PR #480 please?

**Comment by GillesBIANNIC** [comment]
It's better, but there is still a difference in comparison with the "PARTITION way".

With 1600 to the for loop:
0:"Time with REDUCE: 0.028881s"
1:"Time with PARTITION: 0.047194s"
2:"Time with APPLY: 0.405302s"

With 10000:
0:"Time with REDUCE: 0.127254s"
1:"Time with PARTITION: 0.230172s"
2:"Time with APPLY: 12.623684s"

**Comment by hbs** [comment]
This is normal, APPLY does way more things since it has to deal with the ordering of the parameters among others. It will never be on par with the performance of REDUCE. For cases when you want to do a REDUCE, you should not consider APPLY as it adds a lot of overhead

**Comment by hbs** [comment]
That being said, the sort was at the wrong place, you can check the latest #480, it should perform better though still slower than REDUCE

**Comment by GillesBIANNIC** [comment]
Yeah, this is what I want :)
Results with 10000:
0:"Time with REDUCE: 0.236395s"
1:"Time with PARTITION: 0.405102s"
2:"Time with APPLY: 0.416306s"

As you said, reducer is still faster.
To replace a op.add I can use reducer.sum (cf above).
What can I use to replace a op.div ?
I think it's possible to use reducer.product with the opposite of B, but what is the best way to get the opposite of B ?

**Comment by hbs** [comment]
Thanks for the head up, this is a great catch whose solution leads to improved performance for both APPLY and FILTER
