### ISSUE TITLE
UPDATE prevention

### ISSUE THREAD

**Issue by miton18** [senx/warp10-platform#532]
I want to perform some metrics aggregations.
In my mind, I can make a WarpScript which:
1) fetch a GTS
2) Sample it
3) Alter some labels
4) update it

Ex:
```
NOW 'now' STORE
'R_TOKEN'
[ SWAP 'my.metric' {} $now 1 h  ] FETCH
[ SWAP bucketizer.max $now 5 m 0 ] BUCKETIZE
{ 'aggregation' 'hourly' } RELABEL
'W_TOKE' UPDATE
```

I have some errors doing it:
```
 UPDATE can only update Geo Time Series which have been renamed.
```

Beacause of [this if](https://github.com/senx/warp10-platform/blob/67c47a60db35cd9e98665ddd4f710b8fa3a857cf/warp10/src/main/java/io/warp10/script/functions/UPDATE.java#L138)

I understand this security preventing a script to rewrite the same metric, can we enhance it by telling `if !renamed && !labelChanged` ?

**Comment by hbs** [comment]
Simply call NAME and RENAME on your GTS
