### ISSUE TITLE
Add TTL to inserted datapoints

### ISSUE THREAD

**Issue by bubu11e** [senx/warp10-platform#547]
Hi,

Could you add in Warp10 the use of HBase TTL ? It could be an additional header when pushing to  the ingress endpoint for example with a minimum and a maximum value set in the configuration file.

This way, the use of the delete endpoint will be limited to the metadata management and the administration of the warp10 platform would be a lot easier.

Regards,

**Comment by hbs** [comment]
The KafkaDataMessage and WriteToken thrift structures both have attributes placeholders so the most straightforward way of implementing this would be to use a token attribute which would be forwarded in the KafkaDataMessage and interpreted by Store. This is more robust than setting a header which would be limited to clients which can set them.

**Comment by bubu11e** [comment]
Seems ok to me.
