### ISSUE TITLE
Attributes not persisted or not queryable after directory reboots

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#556]
Hello,
   With all Warp 10 version in versions 2.x.x, we identified a strange behavior with Warp 10 attributes: 

   We pushed a new series with a single datapoint, then update it via the Meta endpoint.

```
curl 'http://127.0.0.1:8882/api/v0/update' -d '// testAttributes{} 1'
curl http://127.0.0.1:8882/api/v0/meta -d 'testAttributes{}{test=val}'
```
   At this moment, we can query via the Exec Endpoint our series and we see the attribute, everything is as expected. However when we reboot the directory, this series has no attributes.

   Using a directory in version 1.2.28 resolves the situation. 
   The `parseAttribute` option is not enabled, the `lastActivity` was initially activated, we disable it and it didn't change our result.

On Warp Revision: Revision 2.2.0-6-gad7b4cd8 (Distributed)

We add a log at line https://github.com/senx/warp10-platform/blob/d53296d2ef254732d627079cbd655abf33cee2cd/warp10/src/main/java/io/warp10/continuum/store/Directory.java#L1777 
  
This provides us:
2019-09-27T15:19:47,534 pool-4-thread-6 INFO  store.Directory - ### STORE GTS ATTRS Metadata(name:testAttributes, labels:{.app=test, .producer=..., .owner=...}, classId:8434089792177049908, labelsId:-2729184739603464119, attributes:{test=val}, source:ingress.metadata.update, lastActivity:1569592563765)

The attribute seems to be well send to HBase, but no attributes are available after a directory reboot.

Could you clarify us on what we can dig to resolve this?

**Comment by hbs** [comment]
Hi, thanks for the issue, the incorrect Metadata instance was being serialized, thus leading to the loss of attributes.

A fix was pushed which corrects this issue.
