### ISSUE TITLE
Ability to update sets of attributes

### ISSUE THREAD

**Issue by miton18** [senx/warp10-platform#573]
Actually, when you call `META` or `/api/v0/meta` you have to give the full series selector and the full attributes list to update.

With it:
* Users must know that all attributes are needed to perform a meta update
* To keep old attributes, you need to perform a read operation before a write one, which can cause an override if an update is done between the 2 operations

Do you thing it's possible allow partial update of attributes ?

### Current
```
[ NEWGTS 'os.cpu' RENAME { 'status' 'active' } SETATTRIBUTES ] META
// os.cpu{}{status=active}
```
If `os.cpu` series already have another attributes, there will be lost and replace by `status` one.

### Expected
```
[ NEWGTS 'os.cpu' RENAME { 'status' 'active' } SETATTRIBUTES ] META
// os.cpu{}{status=active}
...
[ NEWGTS 'os.cpu' RENAME { 'processed' '154567890' } SETATTRIBUTES ] META
// os.cpu{}{status=active,processed=154567890}
```

I think this change doesn't need any change on storage layer, *Directory* have all needed attributes locally, they can complete missing attributes on a partial  *meta* request in order to save all attributes on storage like it's done now.

**Comment by hbs** [comment]
The behavior of META or of the current /api/v0/meta endpoint will not be changed. But an optional header to /api/v0/meta and a new WarpScript function could be added.

The support for partial attributes update should be optional.

The case of attribute parsing in the input format should be considered too. Should the /update endpoint allow the same request header as /meta so the semantics of attributes is a partial update too?

Special semantics for removing attributes should be introduced too.

This has to be reflected upon to find the most suitable way forward.

**Comment by miton18** [comment]
What about `/api/v1/meta` for the endpoint ? no need to change the `META` function with it.

But for me yes, if partial meta are allowed on `/meta`, it must be allowed on `/update` (with attribute parsing)

For attributes removing cases, since attributes values is a string, we can handle it with an empty string.
