### ISSUE TITLE
Idea: meta-store

### ISSUE THREAD

**Issue by miton18** [senx/warp10-platform#574]
In the current workflow of Warp10, you have some **Ingress** which produce data on the __data__ topic of Kafka and for new or updated series (metas) some messages to the __metadata__ topic.

Let's focus on metadatas.

Metadatas are consumed by *Directory* to keep an index of all time series.
When consuming this metadata they also forward them to HBase to save them.
When a Directory reboot, it scan HBase to rebuild his cache.

In this configuration every Directory need this own Kafka consumer to build his own series index. 
So, each Directory will perform a *put* on HBase to save his metadata. it do it even if the metadata are the same, because of his dedicated consumer group.

The idea is to remove the role of "persisting metadata on HBase" from the Directory component and build a dedicated component for that.

let's call it `meta-store`

`meta-store` role is to consume metadata from Kafka and perform the **put** on HBase.

## Where is the benefit ?

Each directory, doesn't have to talk to HBase when running (it still need to scan the table on reboot); less pressure; faster message commit on Kafka.

meta-store can have several instances with the same consumer group so every metadata update on HBase is only done once; less pressure on HBase.

**Comment by hbs** [comment]
This is already implemented, check configurations directory.store and directory.delete

**Comment by miton18** [comment]
Well... but not really, `directory.store` and `directory.delete` is half of the job.

With it, you can tell to a **Directory** to not put metadata on HBase, but if you do that on **Directory**s, nobody will handle the job of persisting the metadatas.

So, this is the idea: set `directory.store` and `directory.delete` to false on **Directory**s. And add a dedicated component which consume the __metadata__ topic and only perform the puts on HBase.

This dedicated component is easily scalable because it has only 1 consumer group (vs 1 consumer group per Directory).
Directory is Happy (no put on HBase), HBase is happy too (only 1 put for a metadata vs 1 per directory)

**Comment by hbs** [comment]
Have your serving directories not interact with HBase and set up a dedicated set of Directory instances which will ibteract with HBase but not register and configure then with a black hole directory plugin to not consume memory, this set of Directory instances is your meta store.

**Comment by miton18** [comment]
A directory without legs an and arms might works, Thx !
