### ISSUE TITLE
Avro & schema registry proposal/discuss

### ISSUE THREAD

**Issue by KannarFr** [senx/warp10-platform#599]
Hi @hbs,

WDYT about having a schema registry and gts values with avro schemas?

**Comment by hbs** [comment]
What do you have in mind?

**Comment by KannarFr** [comment]
Manage evolutions on GTS "complex" structure values like json:

* at start values looks like `{"foo": "X"}
* due to evolution of "producer" values become `{"bar":"X"}`

There is no way for "consumer" of this GTS to differentiate the value instead of parse it.

**Comment by hbs** [comment]
You can either store the schema as part of another GTS or decide that your values are Multivariate and store something like [ version '{ ... }' ]

**Comment by KannarFr** [comment]
This way does not ensures that the data is conform to a certain structure, there is no way to validate the data before store it.

**Comment by KannarFr** [comment]
WDYT?

**Comment by hbs** [comment]
Validation should be done prior to pushing the data to Warp 10 which just acts as a dumb storage layer.

**Comment by KannarFr** [comment]
Currently yes, but why it can't be done optionnally by Ingresses?

**Comment by hbs** [comment]
This is too specific for including in ingress, what could be done is to add a plugin mechanism to ingresses which could inspect the data on the ingestion pipeline, you could then write a plugin which would implement this validation, how would that be?

**Comment by KannarFr** [comment]
Plugins have some storage access? It would be nice to manage a schema registry so a way to store schemas.

**Comment by hbs** [comment]
Plugins will be java classes which could do whatever they see fit

**Comment by KannarFr** [comment]
Sure but registry must be shared between plugin instance running on each Ingress.

**Comment by hbs** [comment]
This will be the responsibility of your plugin instances

**Comment by KannarFr** [comment]
Ok.

**Comment by hbs** [comment]
Can you have a look at #601
