### ISSUE TITLE
Attributes in gts fetch

### ISSUE THREAD

**Issue by lucianoBaez** [senx/warp10-platform#608]
Hi guys. I am having trouble getting the attributes in a gts object. When I get the gts the information does not come.

I do the following:

1 - I insert the gts:

Post: http://127.0.0.1:8080/api/v0/update

gts body:
1 / 10.0: 10.0 / 0 test {asid = 51ce2135-ece5-419e-97ee-00570b894c14, arid = de52aec5-9744-4254-a960-4beec783760d, dvid = 7e5d6d42-4106-4691-9e0c-2b080fdeb13d = cdd = dsd = cdd = cdd = cdd = cdd = cdd = cdd = cdd = cdd = cddd Measurement, alid =, assd = 18568cf4-107a-4925-89a8-99b63f2fe511} {rcdt = 1575552190385, _id = ec0db0c4-48ce-473f-b860-0021434d16f9, evdt = 1575552190385} 789

2 - Getting the gts.

Get: http://127.0.0.1:8080/api/v0/fetch?now=now&timespan=-5&selector=~.*{}&format=fulltext&showattr=true&dedup=t&sortmeta=false

Response:

1/9.999999990686774:9.999999990686774/0 prueba{asid=51ce2135-ece5-419e-97ee-00570b894c14,arid=de52aec5-9744-4254-a960-4beec783760d,dvid=7e5d6d42-4106-4691-9e0c-2b080fdeb13d,csid=,.app=noentiendo,evty=Measurement,alid=,assd=18568cf4-107a-4925-89a8-99b63f2fe511}{} 789
1/9.999999990686774:9.999999990686774/0 test{asid=51ce2135-ece5-419e-97ee-00570b894c14,arid=de52aec5-9744-4254-a960-4beec783760d,dvid=7e5d6d42-4106-4691-9e0c-2b080fdeb13d,csid=,.app=noentiendo,evty=Measurement,alid=,assd=18568cf4-107a-4925-89a8-99b63f2fe511}**{}** 789

The attributes section is blank
Could you please help me, I need to search for attribute values

Thank you very much

**Comment by Giwi** [comment]
Hi, add `ingress.parse.attributes = true` in your configuration (or uncomment it).

**Comment by lucianoBaez** [comment]
Thank you very much for the answer, I have several configuration files, could you tell me where this property is located?

![image](https://user-images.githubusercontent.com/10848941/70261386-150ae400-1771-11ea-8a19-a67ecff0f9f4.png)

**Comment by lucianoBaez** [comment]
It worked!!! Add to files

10-egress.conf
10-ingress.conf

In the path: opt / warp10 / etc / conf.d

Thank you very much
