### ISSUE TITLE
Ordering

### ISSUE THREAD

**Issue by lucianoBaez** [senx/warp10-platform#609]
Is it possible to sort by dates, regardless of class and labels?

**Comment by Giwi** [comment]
As explained here: https://www.warp10.io/content/06_Community/01_Introduction, GitHub is the place for bug reporting, but for any question, use stackoverflow or https://groups.google.com/forum/#!forum/warp10-users

Thanks.

**Comment by hbs** [comment]
Please use the aforementioned channels for asking usage question. Closing the issue with the following hint: check the SORT function.
