### ISSUE TITLE
arithmetics on empty GTS

### ISSUE THREAD

**Issue by pi-r-p** [senx/warp10-platform#635]
This code fails:
```
NEWGTS 'no value' RENAME
0.1 *
```

It should return a clone of the empty GTS, but not fail...

**Comment by randomboolean** [comment]
I don't see why not. An empty GTS is not of numeric type.

**Comment by pi-r-p** [comment]
arithmetic between a gts and a constant is a simplification of `mapper.mul`
and so on.
mapper.mul MAP on an empty gts is working.
Testing the number of datapoints before doing arithmetic on gts adds
complexity...
