### ISSUE TITLE
Not Initialising on Windows

### ISSUE THREAD

**Issue by OptrixAU** [senx/warp10-platform#651]
I've installed Warp10 in a Windows environment (yes, I know it's not strongly supported - but for some reason our AMD system working with Docker, even though Hyper-V is enabled in Windows).

The 'WarpInit' function doesn't seem to work as expected. I get no output, and there doesn't seem to be any actual result. No initial tokens are created, no configuration files are copied into **conf.d**, no security hashes generated. 

If I copy the template files over into conf.d (removing '.template' from their filename), set a couple of critical values and run the script that creates the various security keys/hashes, then I can actually //run// the database. But without those initial tokens, there's very little I can actually **do**.

I've installed the system onto my D: drive (d:\Warp10).

Note the init script listed on the web includes the //Warp10// folder **twice**. Not sure if that's required or intentional?

java -Djava.awt.headless=true ^
     -Dlog4j.configuration=file:C:\warp10\etc\log4j.properties ^
     -Xms1g -Xmx1g -XX:+UseG1GC ^
     -cp C:\warp10**\warp10**\etc;C:\warp10\bin\warp10-2.4.0.jar;C:\warp10\lib\* ^
     io.warp10.standalone.WarpInit ^
     C:\warp10\leveldb

**Comment by OptrixAU** [comment]
While this issue is still valid, I eventually figured out what was preventing Docker from functioning - turns out Gigabytes motherboard BIOS does a **really** good job of hiding the option to turn on virtualisation.

**Comment by hbs** [comment]
Closing this issue with this [link](https://www.warp10.io/content/03_Documentation/02_Installation/02_Docker#for-windows-users)
