### ISSUE TITLE
No selector for "Without This Label"

### ISSUE THREAD

**Issue by OptrixAU** [senx/warp10-platform#667]
When renaming series or adding labels, there's a valid case for wanting to erase old data. It would be nice if there was a "does not have label xxx" selector, so that you can select GTS based on the absence of a label.

I added a label (type) to my incoming Warp10 points, and now I'm left with two channels for each measurement channel. For every channel, there's one with the type label, one without.

I'd like to /DELETE all of the untyped points.

A query like **~.*{!type}** would be great - just saying "All series that do _not_  have a type label".

**Comment by hbs** [comment]
At present it is possible to create Geo Time Series with an empty label value. Those series can be retrieved by specifying the empty string as an exact match in a selector, i.e. class{label=}.

We could add a configuration option to change the meaning of the empty label value selector to mean absence of label.

This will have to be explicitly configured so as to avoid deleting the wrong GTS.

**Comment by OptrixAU** [comment]
If empty labels are possible, then it would be better to avoid this exact syntax. Perhaps a different comparison character?

How about **class{label!}**? You already differentiate between '=' and '~' in selectors (at least as part of the mapped version of the WarpScript FETCH function, anyway - the behaviour is slightly different in the non-map version), so adding an additional check for '!' may not be much of an issue?

This way the existing behaviour is maintained, and there's a new syntax that should fit with your existing parsing systems that has a different and distinct meaning?

**Comment by hbs** [comment]
Empty labels are possible but could still be selected using a regular expression (i.e. ~$). Adding a new comparison type would require changes at many different places in the Warp 10 codebase.

The added benefit of using the empty label value for matching absent labels is that it would replicate the same behavior as other systems (e.g. Prometheus).

**Comment by OptrixAU** [comment]
That's fair. 

The only other option would be to compare against a value that indicates 'not present' - like **class{label=\x00}**, which checks for the value of 'label' to be NULL, as distinct from an empty string. This wouldn't break existing installations or require a configuration file setting, and I'm guessing that NULL values aren't valid in labels?

Just trying to find a way to have the feature fit in with existing installations but **not** need a specific configuration option. 

But hey, I'm just throwing ideas out there - really happy that this is being looked into.
