### ISSUE TITLE
Merging GTS on Storage

### ISSUE THREAD

**Issue by OptrixAU** [senx/warp10-platform#668]
Related to the issue #667, it would be nice if there was a way to merge GTSes on-disk that have compatible labels.

For instance, I've got two different channels - **Arm_Pitch{assetid=2, asset=Robot Arm 2}** and **Arm_Pitch{assetid=2, asset=Robot Arm 2, type=disc}**, since I added the 'type' label to my incoming data stream.

Ideally, I'd like to MERGE those on-disk GTSes. 

Alternatively, I'd be happy to RELABEL the one with the missing type, if it had the same net effect of merging the two recording streams.

In fact, WARP10 seems somewhat lacking in administrative functions generally - WarpScript is very interesting and powerful for queries, but if I want to truncate my database, delete measurement channels etc, it's quite cumbersome. Or if these functions DO exist, they're not well explained. Makes it hard to 'sell' to the customer.

**Comment by hbs** [comment]
Geo Time Series are uniquely identifies by their class and set of labels (set of name,value pairs).

Changing the class name or the label set technically identifies another GTS. So what you want to do is retrieve the data from GTS A and push those datapoints to GTS B, then delete A from your Warp 10 instance. There is no merge operation in the Warp 10 Storage Engine, different GTS live separate lives forever, though they may end up with identical datapoints if you do as above.

Truncating a database is possible via DELETE operations or use of the /api/v0/delete endpoint. SenX also offers a commercial extension which adds faster cleaning options for standalone Warp 10 instances.
