### ISSUE TITLE
Dead Series management

### ISSUE THREAD

**Issue by StevenLeRoux** [senx/warp10-platform#674]
There are few ways to manage data retention, and one we’ve pushed in the past was to support TTL so that datapoint can be stored with internal HBase insert time according to this TTL.

In case an operator implement a TTL based data eviction policy, there is a situation that can occur where if a series don’t have any new data points pushed during the TTL period, then  there is no point anymore for a series, but where the series still exist. 

I’ve called this the Dead Series pattern.

It would be nice to have a feature or mecanism to overcome this. I've started a discussion in the groups : https://groups.google.com/forum/#!topic/warp10-users/vG6cFVkOf6g to propose two approaches.

**Comment by hbs** [comment]
Close by merging #690
