### ISSUE TITLE
Bootstrap crash : /etc/rc.status: line 36: SYSTEMD_NO_WRAP: unbound variable

### ISSUE THREAD

**Issue by julienlau** [senx/warp10-platform#679]
Hi,
I tried to install warp10 2.4.0 standalone on an opensuse 15.1 laptop and I have the following error:
/opt/warp10-2.4.0/
[linux-gp75]> sudo ./bin/warp10-standalone.init bootstrap
/etc/rc.status: line 36: SYSTEMD_NO_WRAP: unbound variable

Any hints ?
Note: this is my first attempt to install warp10

Regards

**Comment by pi-r-p** [comment]
It seems really Suse specific.
In the warp10-standalone.sh, we do a `set -euo` . It means that if any script called try to use an undefined variable, it will fail. 
So there is something in Suse needs SYSTEMD_NO_WRAP variable, it will fail.
-Please try to add `SYSTEMD_NO_WRAP=0` at the beginning of warp10-standalone.init, and try again.

**Comment by julienlau** [comment]
Hi,
Thanks it is better, but still... I got an error later.

[root@linux-gp75]> ./bin/warp10-standalone.sh bootstrap
/etc/rc.status: line 113: COLUMNS: unbound variable

For your information I just tested a dummy script with `set -euo` and the dummy script works fine.
```
[root@linux-gp75]> cat test.sh 
set -euo
echo "toto"
echo "toto" > toto
chmod go+rw toto
/opt/warp10-2.4.0/
[root@linux-gp75]> ./test.sh 
allexport       off
braceexpand     on
emacs           off
errexit         on
errtrace        off
functrace       off
hashall         on
histexpand      off
history         off
ignoreeof       off
interactive-comments    on
keyword         off
monitor         off
noclobber       off
noexec          off
noglob          off
nolog           off
notify          off
nounset         on
onecmd          off
physical        off
pipefail        off
posix           off
privileged      off
verbose         off
vi              off
xtrace          off
toto
```

**Comment by pi-r-p** [comment]
OK, thanks for your tests. 
It seems really suse specific, and you're not alone ([here](https://stackoverflow.com/questions/49886768/bash-script-using-rc-status-executing-twice-on-newer-sles) and [there](https://stackoverflow.com/questions/2764962/what-is-rc-status-file-in-linux/2765134) ).
Two choices: You try Warp 10 on another distro... Or you clean your /etc/rc.status... Or you ask Suse why this script is called everytime you sudo something, or create a new user, or try to run something on the name of another user (this is basically what our boostrap do).

I will try openSuse too, to see if we can modify our script without braking the existing compatibility.

**Comment by pi-r-p** [comment]
Fix is simple, just change the beginning of the script warp10-standalone.sh to set failure options after the call to /lib/lsb/init-functions.

I push a fix.

**Comment by pi-r-p** [comment]
see pull request #684
