### ISSUE TITLE
Allow PIVOTing of Encoders

### ISSUE THREAD

**Issue by bensmrs** [senx/warp10-platform#682]
Hi,
To use the PIVOT function after an MVINDEXSPLIT, it seems that we have to convert the Encoders into GTSes. As Encoders are able to store values and labels, it seems that the PIVOT function should be able to take them as an input. What do you think?

**Comment by hbs** [comment]
The algorithm used in PIVOT uses a sweeping line approach which needs the input GTS to be sorted. Encoders cannot be sorted efficiently and heterogeneous encoders cannot be sorted at all, therefore the transformation into GTS would have to be done anyways, ensuring that encoders are homogeneous.

In the mean time, this can be achieved using the following macro (the example is that of https://warp10.io/doc/PIVOT):

NEWENCODER 'C1' RENAME
0 NaN NaN NaN 'A' ADDVALUE
1 NaN NaN NaN 'C' ADDVALUE
3 NaN NaN NaN 'A' ADDVALUE

NEWENCODER 'C2' RENAME
0 NaN NaN NaN 'B' ADDVALUE
2 NaN NaN NaN 'F' ADDVALUE
3 NaN NaN NaN 'B' ADDVALUE

NEWENCODER 'C3' RENAME
0 NaN NaN NaN 1 ADDVALUE
1 NaN NaN NaN 2 ADDVALUE
3 NaN NaN NaN 4 ADDVALUE
4 NaN NaN NaN 5 ADDVALUE

NEWENCODER 'C4' RENAME
0 NaN NaN NaN 10 ADDVALUE
2 NaN NaN NaN 30 ADDVALUE
3 NaN NaN NaN 40 ADDVALUE
4 NaN NaN NaN 50 ADDVALUE

[ 'C1' 'C2' 'C3' 'C4' ] STORE

[ $C3 $C4 ] [ $C1 $C2 ]

<%
  DUP TYPEOF 'GTSENCODER' ==
  <%
    ->GTS
    DUP SIZE 1 == 'Non homogeneous encoder found.' ASSERTMSG
    MAP-> DROP SWAP DROP
  %> IFT
%> '.asgts' STORE
<%
  SAVE '.context' STORE
    [ 'input' 'pivot' ] STORE
    // 
    // Convert Encoders to GTS, ensuring that
    // the encoders were homogeneous (i.e. single type)
    //
    $input <% DROP !$.asgts EVAL %> LMAP
    $pivot <% DROP !$.asgts EVAL %> LMAP
    PIVOT
    ASENCODERS
  $.context RESTORE
%>
EVAL

**Comment by bensmrs** [comment]
Got it! Yes, I came up with a pretty similar approach to deal with it. Is there any other way planned? Like the ability to MVINDEXSPLIT to GTSes if we are guaranteed that the data is homogeneous…
It's not critical, but I feel that the use of PIVOT after MVINDEXSPLIT is quite an obvious choice and should be simple to use (and your article on [TS cardinality](https://blog.senx.io/escaping-the-curse-of-time-series-cardinality/) makes it look like it is). I spent quite some time before figuring that a transformation is needed, and I think that it may slow down the adoption of such a great feature.

**Comment by pi-r-p** [comment]
`->GTS` was modified in 2.4.0 to allow easiest conversion from encoders to gts... See [this article](https://blog.senx.io/howto-warp-10-multivalue-always-easier/) for examples.

**Comment by bensmrs** [comment]
Sure! But to preserve the order of GTSes, it becomes tricky. In my case, I'm dealing with Netflow data and my MV schema is `[ src_ip(STRING) src_port(LONG) dst_ip(STRING) dst_port(LONG) packets(LONG) ]`. Using `->GTS` with a map groups by type and there is AFAIK no trivial way to preserve the original order.

**Comment by pi-r-p** [comment]
Don't you use the renaming facilities that come with MVINDEXSPLIT, then filter out the result by classname ? It is more simple that trying to keep things ordered, especially if one day you add something in the multivalue list. If you trust your inputs type,  `{} ->GTS`  is way more simple than `->GTS`.

**Comment by pi-r-p** [comment]
Did you try `{} ->GTS` after the MVTICKSPLIT ? It keeps the order. 
In you case :
```
$mvgts // list of gts
{
  0 'src_ip'
  1 'src_port'
  2 'dst_ip'
  3 'dst_port'
  4 'packets'
}  // rename output
MVTICKSPLIT // list of list of encoders
<% {} ->GTS %> false LMAP //convert list of encoders to list of gts (order is preserved)

```

**Comment by bensmrs** [comment]
Great! That works fine (but with s/TICK/INDEX/ in your answer). Thanks for your help
