### ISSUE TITLE
Problem with label encoding

### ISSUE THREAD

**Issue by denrou** [senx/warp10-platform#733]
Hi,

I have a python script which calls some warpscript to work on GTS (using py4j module as explained in the documentation). The first part of the python script returns GTS selectors that will be used later. The second part deals with each of them.
The problem I have is that some labels are specific, and there is one case that I can't make it to work.

Let's build a GTS:

```
NEWGTS
{ 'label' 'foo%3Dbar' } RELABEL
'class' RENAME
TOSELECTOR
'selector' STORE

$selector

> ["class{label=foo=bar}"]
```

If I call `PARSESELECTOR` in the same warpscript, everything work as expected:

```
$selector PARSESELECTOR

> [{"label":"=foo=bar"},"class"]
```

However, if the selector is saved in a python variable and sent as a character string to a warpscript, `PARSESELECTOR` is not working as expected (even with proper UTF-8 encoding [as documented](https://warp10.io/content/03_Documentation/03_Interacting_with_Warp_10/03_Ingesting_data/02_GTS_input_format)) :

```
'class{label=foo%3Dbar}' PARSESELECTOR

> [{"label":"=foo"},"class"]
```

Any idea of what is going on?

For information, the version I use is 2.2.0

Thank you

**Comment by hbs** [comment]
When the WarpScript execution environment encounters a STRING definition (characters enclosed in quotes), it will check if the characters include percent encoding, if so it will decode the %hh into the actual characters they represent.

A selector requires that some characters be percent when in class or label name or in label value, namely the equal sign ('=', %3D), the comma (',', %2C) and the closing curly brace ('}', %7D).

In your case your selector STRING only has one level of encoding which is removed by the WarpScript execution environment, the STRING that the call to PARSESELECTOR will be fed as input is 'class{label=foo=bar}', not 'class{label=foo%3Dbar}', you need to have a second level of percent encoding, 'class{label=foo%253Dbar}' if you intend to use the STRING in WarpScript code.

You can use the [SNAPSHOT](https://warp10.io/doc/SNAPSHOT) function to see how the STRING should be rendered in WarpScript code to generate the one you want in the end.

In your example, try $selector SNAPSHOT STOP.

**Comment by denrou** [comment]
Thank you!

If I may suggest to add your comment in the documentation of PARSESELECTOR, it would be really helpful.
