### ISSUE TITLE
Fetch issues in InMemory version

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#778]
Hello, 

Since Warp10 2.5 we encounter FETCH issues when using Warp10 in its InMemory version: 
`
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 ERROR line #1: Exception at &apos;NOW -1 ] =&gt;FETCH&lt;=&apos; in section [TOP] (java.lang.RuntimeException: Error in an underlying parallel scanner. (Error in an underlying parallel scanner. (Negative initial size: -10)))</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /api/v0/exec. Reason:
<pre>    ERROR line #1: Exception at &apos;NOW -1 ] =&gt;FETCH&lt;=&apos; in section [TOP] (java.lang.RuntimeException: Error in an underlying parallel scanner. (Error in an underlying parallel scanner. (Negative initial size: -10)))</pre></p>
</body>
</html>
`

The query is simply:
`
[ 'TOKEN' 'test' {} NOW -1 ] FETCH
`

**Comment by hbs** [comment]
Which version of the in memory store are you using, the chunked one or the legacy?

Can you provide the output of <% FETCH %> <% ERROR %> <% %> TRY so we can see the whole stack trace.

**Comment by aurrelhebert** [comment]
We still use the chunked one

**Comment by hbs** [comment]
What is the chunk count per GTS? Can you share the values of warp.standalone.inmemory.* metrics from a faulty instance?

**Comment by aurrelhebert** [comment]
[[{"stacktrace":[["MemoryWarpScriptStack.java",979,"io.warp10.script.MemoryWarpScriptStack","exec"],
["TRY.java",58,"io.warp10.script.functions.TRY","apply"],
["MemoryWarpScriptStack.java",857,"io.warp10.script.MemoryWarpScriptStack","exec"],
["EgressExecHandler.java",269,"io.warp10.continuum.egress.EgressExecHandler","handle"],
["GzipHandler.java",561,"org.eclipse.jetty.server.handler.gzip.GzipHandler","handle"],
["HandlerList.java",52,"org.eclipse.jetty.server.handler.HandlerList","handle"],
["HandlerWrapper.java",132,"org.eclipse.jetty.server.handler.HandlerWrapper","handle"],
["Server.java",564,"org.eclipse.jetty.server.Server","handle"],
["HttpChannel.java",320,"org.eclipse.jetty.server.HttpChannel","handle"],
["HttpConnection.java",251,"org.eclipse.jetty.server.HttpConnection","onFillable"],
["AbstractConnection.java",279,"org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded"],
["FillInterest.java",110,"org.eclipse.jetty.io.FillInterest","fillable"],
["ChannelEndPoint.java",124,"org.eclipse.jetty.io.ChannelEndPoint$2","run"],
["QueuedThreadPool.java",672,"org.eclipse.jetty.util.thread.QueuedThreadPool","runJob"],
["QueuedThreadPool.java",590,"org.eclipse.jetty.util.thread.QueuedThreadPool$2","run"],
["Thread.java",748,"java.lang.Thread","run"]],"type":"class io.warp10.script.WarpScriptException","message":"Exception at 'FETCH' in section '[TOP]'"},
{"stacktrace":[["FETCH.java",668,"io.warp10.script.functions.FETCH","apply"],
["MemoryWarpScriptStack.java",956,"io.warp10.script.MemoryWarpScriptStack","exec"],
["TRY.java",58,"io.warp10.script.functions.TRY","apply"],
["MemoryWarpScriptStack.java",857,"io.warp10.script.MemoryWarpScriptStack","exec"],
["EgressExecHandler.java",269,"io.warp10.continuum.egress.EgressExecHandler","handle"],
["GzipHandler.java",561,"org.eclipse.jetty.server.handler.gzip.GzipHandler","handle"],
["HandlerList.java",52,"org.eclipse.jetty.server.handler.HandlerList","handle"],
["HandlerWrapper.java",132,"org.eclipse.jetty.server.handler.HandlerWrapper","handle"],
["Server.java",564,"org.eclipse.jetty.server.Server","handle"],["HttpChannel.java",320,"org.eclipse.jetty.server.HttpChannel","handle"],
["HttpConnection.java",251,"org.eclipse.jetty.server.HttpConnection","onFillable"],
["AbstractConnection.java",279,"org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded"],
["FillInterest.java",110,"org.eclipse.jetty.io.FillInterest","fillable"],
["ChannelEndPoint.java",124,"org.eclipse.jetty.io.ChannelEndPoint$2","run"],
["QueuedThreadPool.java",672,"org.eclipse.jetty.util.thread.QueuedThreadPool","runJob"],
["QueuedThreadPool.java",590,"org.eclipse.jetty.util.thread.QueuedThreadPool$2","run"],
["Thread.java",748,"java.lang.Thread","run"]],
"type":"class io.warp10.script.WarpScriptException","message":"java.lang.RuntimeException: Error in an underlying parallel scanner."},
{"stacktrace":[["ParallelGTSDecoderIteratorWrapper.java",433,"io.warp10.continuum.store.ParallelGTSDecoderIteratorWrapper","hasNext"],
["FETCH.java",469,"io.warp10.script.functions.FETCH","apply"],["MemoryWarpScriptStack.java",956,"io.warp10.script.MemoryWarpScriptStack","exec"],
["TRY.java",58,"io.warp10.script.functions.TRY","apply"],["MemoryWarpScriptStack.java",857,"io.warp10.script.MemoryWarpScriptStack","exec"],
["EgressExecHandler.java",269,"io.warp10.continuum.egress.EgressExecHandler","handle"],
["GzipHandler.java",561,"org.eclipse.jetty.server.handler.gzip.GzipHandler","handle"],
["HandlerList.java",52,"org.eclipse.jetty.server.handler.HandlerList","handle"],
["HandlerWrapper.java",132,"org.eclipse.jetty.server.handler.HandlerWrapper","handle"],
["Server.java",564,"org.eclipse.jetty.server.Server","handle"],["HttpChannel.java",320,"org.eclipse.jetty.server.HttpChannel","handle"],
["HttpConnection.java",251,"org.eclipse.jetty.server.HttpConnection","onFillable"],
["AbstractConnection.java",279,"org.eclipse.jetty.io.AbstractConnection$ReadCallback","succeeded"],
["FillInterest.java",110,"org.eclipse.jetty.io.FillInterest","fillable"],
["ChannelEndPoint.java",124,"org.eclipse.jetty.io.ChannelEndPoint$2","run"],
["QueuedThreadPool.java",672,"org.eclipse.jetty.util.thread.QueuedThreadPool","runJob"],
["QueuedThreadPool.java",590,"org.eclipse.jetty.util.thread.QueuedThreadPool$2","run"],
["Thread.java",748,"java.lang.Thread","run"]],"type":"class java.lang.RuntimeException","message":"Error in an underlying parallel scanner."},
{"stacktrace":[["ByteArrayOutputStream.java",74,"java.io.ByteArrayOutputStream","<init>"],
["GTSEncoder.java",266,"io.warp10.continuum.gts.GTSEncoder","<init>"],
["InMemoryChunkSet.java",473,"io.warp10.standalone.InMemoryChunkSet","fetchCountEncoder"],
["InMemoryChunkSet.java",264,"io.warp10.standalone.InMemoryChunkSet","fetchEncoder"],
["InMemoryChunkSet.java",217,"io.warp10.standalone.InMemoryChunkSet","fetch"],
["StandaloneChunkedMemoryStore.java",218,"io.warp10.standalone.StandaloneChunkedMemoryStore$2","hasNext"],
["ParallelGTSDecoderIteratorWrapper.java",133,"io.warp10.continuum.store.ParallelGTSDecoderIteratorWrapper$GTSDecoderIteratorRunnable","run"],
["ThreadPoolExecutor.java",1149,"java.util.concurrent.ThreadPoolExecutor","runWorker"],
["ThreadPoolExecutor.java",624,"java.util.concurrent.ThreadPoolExecutor$Worker","run"],
["Thread.java",748,"java.lang.Thread","run"]],"type":"class java.lang.IllegalArgumentException","message":"Negative initial size: -10"}]

**Comment by hbs** [comment]
Ok, thanks, merged a fix.

**Comment by aurrelhebert** [comment]
Great I will test it :)

**Comment by aurrelhebert** [comment]
Thanks for this patch, it's fixing the issue
