### ISSUE TITLE
The StreamUpdate endpoint seems broken

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#779]
With Warp10 version 2.5, the StreamUpdate endpoint seems broken. I reverted the StreamUpdateHandler code change (up to  https://github.com/senx/warp10-platform/commit/833dbfce826c195f6e327b0aa7f41dc10c4ec1f7#diff-12e557513125c28d90290ebab99f2a9c) on our side to make it work.

**Comment by hbs** [comment]
What faulty behavior are your noticing?

**Comment by aurrelhebert** [comment]
When we send Metrics we receive a "NullPointerException" instead of the expected OK (TOKEN step is OK)

**Comment by hbs** [comment]
Is this behavior on the standalone or distributed version? What is the sequence leading to the NPE? Is TOKEN called correctly prior to pushing data?
