### ISSUE TITLE
Bad behavior of a script with a String as Value (but works fine with an integer)

### ISSUE THREAD

**Issue by pbuleon** [senx/warp10-platform#807]
Hi,

Here is a small script.
At the line 36, if I use an integer, it works fine. But if I replace it by a String, it doesn't work at all!

// create a new GTS : a travel
NEWGTS
1 10
<%
 44.843700 -0.603911 NaN true ADDVALUE // ok it's a static travel !
%>
FOR
"travel" STORE

// create a second gts containing town locations
NEWGTS
1 44.843700 -0.603911 NaN "Town1" ADDVALUE
2 40.392783 -5.723980 NaN "Town2" ADDVALUE
"locations" RENAME "locations" STORE
$locations

// loop on the locations
<%
  DUP 1 GET "LocLat" STORE // store lat of the town
  DUP 2 GET "LocLong" STORE // store long of the town
  4 GET "LocName" STORE  // store name of the town
  // for each point of the travel, calculate the distance to the town
  [ 
  $travel 
  <%
    'mapping_window' STORE
    $mapping_window 0 GET "tick" STORE // tick of the trave
    $mapping_window 4 GET 0 GET "lat" STORE // lat of the travel
    $mapping_window 5 GET 0 GET "long" STORE // long of the travel
    $tick 
    $lat
    $long
    NaN
    // ****************************************************************************
    2 // fake distance. With an Integer it is OK, but it does'nt work with a STRING
    // '2' // with a string it doesn't work !
    // ****************************************************************************
    %> MACROMAPPER
    0 0 0
  ] MAP
    "distance_" $LocName + RENAME
  [ SWAP 400000 mapper.le 0 0 0 ] MAP
 %>
FOREACH

************************************************************************************************
And if I comment the line 26 and uncomment the line 37 ( Replace 2 by '2') It stop working
// create a new GTS : a travel
NEWGTS
1 10
<%
 44.843700 -0.603911 NaN true ADDVALUE // ok it's a static travel !
%>
FOR
"travel" STORE

// create a second gts containing town locations
NEWGTS
1 44.843700 -0.603911 NaN "Town1" ADDVALUE
2 40.392783 -5.723980 NaN "Town2" ADDVALUE
"locations" RENAME "locations" STORE
$locations

// loop on the locations
<%
  DUP 1 GET "LocLat" STORE // store lat of the town
  DUP 2 GET "LocLong" STORE // store long of the town
  4 GET "LocName" STORE  // store name of the town
  // for each point of the travel, calculate the distance to the town
  [ 
  $travel 
  <%
    'mapping_window' STORE
    $mapping_window 0 GET "tick" STORE // tick of the trave
    $mapping_window 4 GET 0 GET "lat" STORE // lat of the travel
    $mapping_window 5 GET 0 GET "long" STORE // long of the travel
    $tick 
    $lat
    $long
    NaN
    // ****************************************************************************
    // 2 // fake distance. With an Integer it is OK, but it does'nt work with a STRING
    '2' // with a string it doesn't work !
    // ****************************************************************************
    %> MACROMAPPER
    0 0 0
  ] MAP
    "distance_" $LocName + RENAME
  [ SWAP 400000 mapper.le 0 0 0 ] MAP
 %>
FOREACH

Have you already seen such behavior?

**Comment by hbs** [comment]
Can you be more precise as to what "doesn't work"? The MAP operation following the MAP applying your MACROMAPPER is doing a nunerical comparison, so it should be expected that this operation fails if the GTS it attempts to operate on has STRING values.

Is that what the error message is telling you?

**Comment by pbuleon** [comment]
Hi,
Yes the input Gts has integre value. But i'd like to modify the type to string in the result of the macro.
Does it mean it is not possible to modify the type?

thanks

**Comment by hbs** [comment]
You can modify the type, but since you are applying a mapper (mapper.le) which will return false when you compare a STRING with a number, changing 2 into '2' will lead to an empty GTS after your last MAP operation. This is certainly not a bug but the expected behavior of the mapper.le mapper.

**Comment by pbuleon** [comment]
Hi,
Ok I see my error !
It is due to the  [ SWAP 400000 mapper.le 0 0 0 ] MAP
I totally forgot this line!
Sorry
