### ISSUE TITLE
Could not raise an exception with an Invalid payload

### ISSUE THREAD

**Issue by aurrelhebert** [senx/warp10-platform#861]
I try to push in Warp 10 a string data point of size 96768, when I explicitly set our ingress limit to 65536.
```yaml
# Maximum value size
ingress.value.maxsize = 65536
```
I expected a Parse error as result, or I do get a 200 as response status code (and of course my data point isn't pushed)

**Comment by hbs** [comment]
What is the version of Warp 10 you are using?

**Comment by aurrelhebert** [comment]
We use the 2.5, on my check, I didn't find any update on this part of the code

**Comment by ftence** [comment]
I can't reproduce this issue on master or 2.5.0, either on standalone or distributed with:
```
curl -v -H "X-Warp10-Token:WRITE" --data-binary "0// iss.861{} 'looooo...oooong'" http://127.0.0.1:8882/api/v0/update`
```
With `looooo...oooong` a 66k character-long value.

All my tests got this return status:
```
HTTP/1.1 500 Error when updating data: Parse error at '0// iss.861{} 'loooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo...oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooong'' (Value too large for GTS )
```

**Comment by hbs** [comment]
Any update on your side @aurrelhebert? Or shall we close the issue since we cannot reproduce it on any of the versions from 2.5.0 upward?

**Comment by aurrelhebert** [comment]
Thanks for checking... I will need to dive more on my side to see if it's a side effect of an other config parameter or something else. As you can't reproduce it on 2.5.0 or more version, I close this issue for the moment
