### ISSUE TITLE
Distributed directory crashing due to JNI

### ISSUE THREAD

**Issue by urcadox** [senx/warp10-platform#956]
Hello everyone,

We are experiencing a recurring issue on our Directory instances where they seem to try and use JNI which is not built into the JRE, hence the JVM crashes due to a segfault.

I have the full crash logs of 7 of these.

It seems to happen at random, sometimes a couple of days after starting, sometimes a few weeks.

Here is the timing info + exceptions: [warp10-directory-distributed-jni-issue.txt](https://github.com/senx/warp10-platform/files/6351067/warp10-directory-distributed-jni-issue.txt)

I'm under the impression that JNI should only be used for native leveldb in the standalone version. Is there something I'm not aware of in the directory?

All nodes are running Warp10 2.7.1 (with a [patch](https://github.com/senx/warp10-platform/files/6351125/warp10-2.7.1-patch-gts-skip.txt) which skips some GTS during the initial HBase scan which most definitely does not have any impact on this matter).

I'm happy to provide more info about this and to try patches, it seems we should only have to wait for a few weeks at most to get more info / see if the issue is resolved.

Thank you for your time.

**Comment by hbs** [comment]
Do you experience the same issue when running Warp 10 with the JDK?

**Comment by urcadox** [comment]
I'm not sure I understand, I only said "JRE" to mean the running part of the JDK. A full JDK is installed.

We are using an older Icedtea build though, I could test with an updated JDK. Although this could fix the issue, my question still stands though: is the distributed version somehow using a leveldb related feature from the standalone one (I have my doubts about the stats endpoint)?

**Comment by hbs** [comment]
The answer to your question is no, the distributed version of Warp 10 does not use LevelDB in any aspect.

**Comment by hbs** [comment]
Any new development on your side regarding this issue?

**Comment by urcadox** [comment]
All directory nodes now have an up-to-date OpenJDK 8. It's been a bit more than 2 days, no crash for now. We'll see what happens in the coming 2-3 weeks.

**Comment by hbs** [comment]
Closing the issue for now then, re-open it if the problem arises again.
