### ISSUE TITLE
Max ops error message not passed on since last revision

### ISSUE THREAD

**Issue by randomboolean** [senx/warp10-platform#995]
The error message when reaching max ops is not passed on anymore.

With rev 2.8.1:
`line #1: Exception at '<% + %> =>FOR<=' in section [TOP]`

With rev 2.7.5
`line #1: Exception at '<% + %> =>FOR<=' in section [TOP] (Exception in section '[TOP]' (Operation count (1001) exceeded maximum of 1000))`

**Comment by ftence** [comment]
Already fixed by #982.
